language: node_js
node_js:
- '0.8'
cache:
  directories:
  - node_modules
notifications:
  flowdock:
  - secure: "EcnNczlehdwHapm1iKt9gUesSeoHu0BHdmSmqvgsxFiO0bikTh55jtVPt/GtQzLel4qMY/6TQtAWdraNBqlyBahaXDjxRqvg5EPLq1nP2yeiz8YfvvbyLQNU9KDwU4HncyO/purcUKC6KcSEopp/neUzDFdjzlVpbzeLOF6Rj4I="
