language: node_js
node_js:
- '0.8'
after_script:
  - travis-notify-geckoboard -a $GECKOBOARD_API_KEY -w $GECKOBOARD_WIDGET_KEY
before_script:
  - npm install -g travis-notify-geckoboard
  - mkdir $HOME/.browserstack
  - curl -o $HOME/.browserstack/BrowserStackTunnel.jar http://www.browserstack.com/BrowserStackTunnel.jar
  - 'echo "{\"username\": \"$BROWSERSTACK_USERNAME\", \"password\": \"$BROWSERSTACK_PASSWORD\", \"apiKey\": \"$BROWSERSTACK_KEY\"}" > $HOME/.browserstack/browserstack.json'
cache:
  directories:
  - node_modules
env:
  global:
  - secure: "CJUqdUkFyce7OTzn/bxSUP13SMl+QxDy3lOZrDHaUy9clhVXXDw8PCspeg6jXMcIQisgRtWHhpN0CvUX0lj4ARRLrPQloBviuv14O4wtdtiZN9rzETvRB/odzUIK5hS1yzCCSKV8BN2D+rCxHEX2Ukdtgj1eYWM7dLITtfDC7Rk=" # GECKOBOARD_API_KEY
  - secure: "js0gyIrJ5Ll/B4KfMLf2MvTHj09OMjfD0ZA24kuc9RyO3n+tw0LLxgrhqBtcuH0L55m1n0SiL96P6IecNEzfLAcLArMNrqjTG9frmQjw1vR84HtOGydDFfXeqlFEbGFRfhEi10lxgVJvm07NN5tTSVXb1GJeM38iS1rv/v+udls=" # GECKOBOARD_WIDGET_KEY
  - secure: "R197Fq2CvJGKvCqY0p7JdXFw8g45JW39ynJV5XGBLvwaFSBdNbkSP2m/M6UBn80ZWNfilFW2ftuFvDdrkRBpPBo5Q1LjWAgAKbUz4iGyJlUFF2Sia05359099YubAOjjg/7c3DA4fDoYkv/A60eOWPKSkJLeaAqXq2Oyi0HSbuw=" # BROWSERSTACK_USERNAME
  - secure: "YGIA4PSSzpudc0D/5/Rb2/snx4zKQRE3sEuu/nJCQitNaasok4Wwp52XIFIpIRk72A550zomLsuIpFO0aq5I9Pc4dMy19jw38CBIyxMWbth/WvjhtOKrlCtgr8aJP6V07vIouO4fEQN5F/s2E71BladMVexjimo0kZ3ibIQykiY=" # BROWSERSTACK_PASSWORD
  - secure: "aI2DO1qyRdas1MKG2i0A7fMuzDJMlN5ssdhks4QVoy4pnacDZEdJ1Zm4uSAdjs2ezv2LSbBcLDn7sbR0xEganhXydAdm8gHgyY0qigwUE6mLGXjtarJg7wENB3WZ2DPkNEj5ZLtmlzjOEbmnV2u7AXHIyC/H3Ex0E7Cvg8BIO4A=" # BROWSERSTACK_KEY
notifications:
  flowdock:
  - secure: "EcnNczlehdwHapm1iKt9gUesSeoHu0BHdmSmqvgsxFiO0bikTh55jtVPt/GtQzLel4qMY/6TQtAWdraNBqlyBahaXDjxRqvg5EPLq1nP2yeiz8YfvvbyLQNU9KDwU4HncyO/purcUKC6KcSEopp/neUzDFdjzlVpbzeLOF6Rj4I="
